  com:
    hhao:
      config:
        #全局上下文配置
        app-context:
          enable: true
        #生命周期
        app-smart-lifecycle:
          enable: true
        #消息文件配置
        message-source:
          enable: true
        #元数据配置
        metadata:
          enable: true
        #validator配置
        validator:
          enable: true
        #统一返回结果设置
        result:
          #默认状态值设置
          status:
            succeed: 200
            error: 500
          #默认提示消息设置
          msg:
            succeed: succeed
            error: error
      #aop,安全过滤要开启
      aop:
        pointcut: "execution(* com.hhao.common.springboot.web.mvc.test.api.*.*(..))"
        enable-safe-filter: true
      #xss安全过滤的配置文件
      xss:
        policy: classpath:antisamy.xml

